Repository Hihthei/Mood-based-musics-movies, pull requests merged in 2024-12, with the labels that each got.

#12 :tada: Features/music movie viewer
  Source/App/App.py
  Source/App/MainPage.py
  Source/Database/database.py
Labels: Features

#13 :recycle: Refacto/Tkinter to CustomTkinter
  Source/App/App.py
  Source/App/Connect.py
  Source/App/FirstPage.py
  Source/App/MainPage.py
  Source/App/NewUser.py
  Source/App/PlaylistManager.py
Labels: Refacto

#14 Database user add and remove + sql files
  Source/Database/database.py
  delete_table_database.sql
  init_value.sql
  quiery_init.sql
Labels: Features

#15 🛝 Rebase/UI_Playlist
  Source/Database/database.py
  delete_table_database.sql
  init_value.sql
  quiery_init.sql
Labels: Refacto

#16 Features/Connection_UI_DB
  Source/App/Connect.py
  Source/App/NewUser.py
  Source/Database/DBCommunicate.py
  tests/Database/test_database.py
Labels: Features

#17 🦖 FIxes DBConnection + Features DBError handler
  Source/App/App.py
  Source/App/Connect.py
  Source/App/NewUser.py
  Source/Database/DBCommunicate.py
  Source/Security/DBCommunicate.py
Labels: Features, Fix

#19 🎉 Features/playlist manager
  Source/Database/DBCommunicate.py
  init_value.sql
  quiery_init.sql
Labels: Features, Fix

#20 Rebase/ from UI playlist
  Source/Database/DBCommunicate.py
  init_value.sql
  quiery_init.sql
Labels: Refacto
